import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@common/prisma.service';
import * as PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private readonly exportsDir: string;

  constructor(private readonly prisma: PrismaService) {
    this.exportsDir = path.join(process.cwd(), 'uploads', 'exports');
    if (!fs.existsSync(this.exportsDir)) {
      fs.mkdirSync(this.exportsDir, { recursive: true });
    }
  }

  async generateVisaFile(applicationId: string): Promise<string> {
    const application = await this.prisma.visaApplication.findUnique({
      where: { id: applicationId },
      include: {
        client: true,
        destinationCountry: true,
        documents: true,
        createdBy: { select: { firstName: true, lastName: true } },
      },
    });

    if (!application) {
      throw new NotFoundException('Visa application not found');
    }

    const fileName = `VisaFile_${application.applicationNumber}_${Date.now()}.pdf`;
    const filePath = path.join(this.exportsDir, fileName);

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Header
    doc.fontSize(24).text('Visa Application File', 50, 50);
    doc.fontSize(12).text(`Application: ${application.applicationNumber}`, 50, 80);
    doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, 50, 95);
    doc.moveDown(2);

    // Client Info
    doc.fontSize(16).text('Applicant Information', { underline: true });
    doc.fontSize(11);
    doc.text(`Name: ${application.client.firstName} ${application.client.lastName}`);
    doc.text(`Passport: ${application.client.passportNumber || 'N/A'}`);
    doc.text(`Nationality: ${application.client.nationality || 'N/A'}`);
    doc.text(`Date of Birth: ${application.client.dateOfBirth ? new Date(application.client.dateOfBirth).toLocaleDateString('en-GB') : 'N/A'}`);
    doc.moveDown(1);

    // Travel Info
    doc.fontSize(16).text('Travel Information', { underline: true });
    doc.fontSize(11);
    doc.text(`Destination: ${application.destinationCountry.name}`);
    doc.text(`Entry Type: ${application.entryType || 'N/A'}`);
    doc.text(`Duration: ${application.durationOfStay ? application.durationOfStay + ' days' : 'N/A'}`);
    doc.text(`Intended Entry: ${application.intendedDateOfEntry ? new Date(application.intendedDateOfEntry).toLocaleDateString('en-GB') : 'N/A'}`);
    doc.text(`Intended Exit: ${application.intendedDateOfExit ? new Date(application.intendedDateOfExit).toLocaleDateString('en-GB') : 'N/A'}`);
    doc.moveDown(1);

    // Documents List
    doc.fontSize(16).text('Attached Documents', { underline: true });
    doc.fontSize(11);
    if (application.documents.length === 0) {
      doc.text('No documents attached.');
    } else {
      application.documents.forEach((docItem, index) => {
        doc.text(`${index + 1}. ${docItem.type} - ${docItem.originalName} (${docItem.status})`);
      });
    }
    doc.moveDown(1);

    // Footer
    doc.fontSize(10).text('Generated by Visa File Builder', 50, doc.page.height - 80);
    doc.text(`Prepared by: ${application.createdBy?.firstName || ''} ${application.createdBy?.lastName || ''}`, 50, doc.page.height - 65);

    doc.end();

    await new Promise<void>((resolve, reject) => {
      stream.on('finish', resolve);
      stream.on('error', reject);
    });

    // Update application
    await this.prisma.visaApplication.update({
      where: { id: applicationId },
      data: {
        generatedPdf: `/uploads/exports/${fileName}`,
        generatedAt: new Date(),
      },
    });

    this.logger.log(`Generated visa file: ${fileName}`);
    return filePath;
  }

  async generateFormPreview(applicationId: string): Promise<Buffer> {
    const application = await this.prisma.visaApplication.findUnique({
      where: { id: applicationId },
      include: { client: true, destinationCountry: true },
    });

    if (!application) {
      throw new NotFoundException('Visa application not found');
    }

    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({ margin: 50, size: 'A4' });

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Form Header
      doc.fontSize(20).text(`Visa Application Form - ${application.destinationCountry.name}`, 50, 50, { align: 'center' });
      doc.moveDown(2);

      // Form Fields
      doc.fontSize(12);
      const formData = application.formData as any || {};

      Object.entries(formData).forEach(([key, value]) => {
        doc.text(`${key}: ${value || 'N/A'}`, { continued: false });
      });

      if (Object.keys(formData).length === 0) {
        doc.text('No form data available.', { align: 'center' });
      }

      doc.end();
    });
  }
}
